version: '2'
services:
    retrojobweb-app:
        image: retrojobweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://retrojobweb-mysql:3306/retrojobweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=retrojobweb-elasticsearch:9300
        ports:
            - 8080:8080
    retrojobweb-mysql:
        extends:
            file: mysql.yml
            service: retrojobweb-mysql
    retrojobweb-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: retrojobweb-elasticsearch
